spring:
  profiles:
    active: dev

  config:
    import: classpath:secret.properties

  datasource:
    master:
      url: jdbc:mariadb://localhost:3306/master
      ## url: rds 주소
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver
      pool-name: master-pool

    tenant:
      url: jdbc:mariadb://localhost:3306/
      ## url: rds 주소
      driver-class-name: org.mariadb.jdbc.Driver
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      minimum-idle: 3
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 30000
      pool-name: tenant-pool

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

token:
  secret: ${SECRET_KEY}
  access_expiration_time: 36000000      # Access Token: 15분 (900,000ms)
  refresh_expiration_time: 604800000  # Refresh Token: 7일 (604,800,000ms)